imports:
    - { resource: admin.yml }

pimcore:
    objects:
        class_definitions:
            data:
                map:
                    coreShopTaxRuleGroup: CoreShop\Bundle\TaxationBundle\CoreExtension\TaxRuleGroup
                    coreShopTaxRate: CoreShop\Bundle\TaxationBundle\CoreExtension\TaxRate

jms_serializer:
    metadata:
        directories:
            coreshop-taxation:
                namespace_prefix: "CoreShop\\Component\\Taxation"
                path: "@CoreShopTaxationBundle/Resources/config/serializer"
