coreshop_admin_tax_rate:
  type: coreshop.resources
  resource: |
    alias: coreshop.tax_rate

coreshop_admin_tax_rule_group:
  type: coreshop.resources
  resource: |
    alias: coreshop.tax_rule_group

coreshop_admin_tax_rule_group_list_rules:
  path: /%coreshop.admin.route.base%/tax_rule_groups/list-rules
  defaults: { _controller: 'coreshop.admin_controller.tax_rule_groups:listRulesAction'}